### ISSUE TITLE
Custom Format and Formula - should be text area

### ISSUE THREAD

**Issue by cjestavillo** [CradlePHP/Cradle#10]

**Comment by cjestavillo** [comment]
![image](https://user-images.githubusercontent.com/33796130/38303357-70403d58-3838-11e8-8fe3-37bdcfb78d17.png)

**Comment by cjestavillo** [comment]
Email and Phone are made into text area as well...
![image](https://user-images.githubusercontent.com/33796130/38404137-814baca0-399a-11e8-8dd9-e64a4741574a.png)

**Comment by cblanquera** [comment]
Verified
