### ISSUE TITLE
System Package - Summation Function

### ISSUE THREAD

**Issue by JosephFidelino** [CradlePHP/Cradle#100]
Create a function in the system package that is used to get the sum of a column in an entire table

**Comment by jayn0rm** [comment]
Expected output as discussed:

<img width="508" alt="screen shot 2018-05-30 at 2 15 29 pm" src="https://user-images.githubusercontent.com/15950561/40703425-a88ae9c8-6417-11e8-8166-ae2d0e0b4e43.png">

**Comment by JosephFidelino** [comment]
No need to do this. Total can be displayed in Pipeline.

https://github.com/CradlePHP/Cradle/issues/76
