### ISSUE TITLE
price fields should be aligned right especially on tables

### ISSUE THREAD

**Issue by aprilsacil** [CradlePHP/Cradle#110]

**Comment by aprilsacil** [comment]
https://github.com/aprilsacil/cradle-system/commit/e59d61b451b88baedd5103e0fd1bf1387f4acf1e

**Comment by JosephFidelino** [comment]
Tested. Good to close.

![image](https://user-images.githubusercontent.com/26085313/41526622-5992be5e-7317-11e8-9976-c6c3ec1d1b0b.png)
