### ISSUE TITLE
Pipeline - Moving of Card from 1 Status to Another

### ISSUE THREAD

**Issue by JosephFidelino** [CradlePHP/Cradle#121]
![image](https://user-images.githubusercontent.com/26085313/41086753-8e0e5d58-6a6d-11e8-9cf5-da409752154d.png)
![image](https://user-images.githubusercontent.com/26085313/41086768-99315e7e-6a6d-11e8-8754-c5e4cad9c319.png)

**Comment by JosephFidelino** [comment]
Upon moving card from column to another is working but upon refresh, card still returns to its previous column. Example: Moving card from Pending to Approved. Upon refreshing, card was still on Pending.

**Comment by aprilsacil** [comment]
unable to recreate

**Comment by JosephFidelino** [comment]
Retested. Seems to be issue was fix upon doing either cloning a new project or composer update. We can close this ticket for the meantime.

![image](https://user-images.githubusercontent.com/26085313/41585913-f5e58f7c-73dd-11e8-896f-06a8ba3b0222.png)
