### ISSUE TITLE
Pipeline - Moving of Card - Error Notification

### ISSUE THREAD

**Issue by JosephFidelino** [CradlePHP/Cradle#130]
Display a toast message if there's an error when doing moving of cards

![image](https://user-images.githubusercontent.com/26085313/41525306-1c5e15b4-7313-11e8-8d02-20b96270744b.png)

**Comment by aprilsacil** [comment]
unable to recreate.

**Comment by JosephFidelino** [comment]
Retested. Seems to be issue was fix upon doing either cloning a new project or composer update. We can close this ticket for the meantime.

![image](https://user-images.githubusercontent.com/26085313/41585918-f8631a44-73dd-11e8-9f3f-0c924eed05b1.png)
