### ISSUE TITLE
Relation - Upload CSV not working

### ISSUE THREAD

**Issue by JosephFidelino** [CradlePHP/Cradle#149]
Currently, `subcategory_id = 1` is only linked to `category_id = 1`. I'm trying to upload `subcategory_id = 2` link to `category_id = 1`. Upon import, system display success notification but doesn't reflect the linked of the new subcategory.

![image](https://user-images.githubusercontent.com/26085313/42488942-d2be7708-843a-11e8-9d67-19836c9aaaad.png)
![image](https://user-images.githubusercontent.com/26085313/42488945-d7ef038c-843a-11e8-990e-547852eac298.png)
![image](https://user-images.githubusercontent.com/26085313/42488974-f5d86bf4-843a-11e8-8336-8b88699af428.png)

**Comment by mimontoy1** [comment]
Regarding #149, I understood the task but I can't see "Inventory" menu in my setup.
![cradle149](https://user-images.githubusercontent.com/40560725/51243200-266fb580-193f-11e9-9daf-5fcd51ec0292.png)

**Comment by mimontoy1** [comment]
As I have debugged while import CSV it is parsed correctly and requests also come with correct data
But when it is saved on DB it is stored as NULL though new row is created

**Comment by teamw-synapse** [comment]
Started working on this task.
