### ISSUE TITLE
System: Improper Use of 'admin-render-page' in Schema/controller.php

### ISSUE THREAD

**Issue by cblanquera** [CradlePHP/Cradle#164]
https://github.com/CradlePHP/cradle-system/blob/master/src/Schema/controller.php#L752
https://github.com/CradlePHP/cradle-system/blob/master/src/Schema/controller.php#L186

should be using the following instead.
```
//render page
$this->trigger('admin-render-page', $request, $response);
```

**Comment by cjzamora** [comment]
Done.

Commit: https://github.com/CradlePHP/cradle-system/commit/9daf6a4bb975afa7f935abd3a13387ce8ccc1245
