### ISSUE TITLE
System: Using Model's javadoc in Schema/controller.php

### ISSUE THREAD

**Issue by cblanquera** [CradlePHP/Cradle#165]
Shows this on https://github.com/CradlePHP/cradle-system/blob/master/src/Schema/controller.php#L79-L84
```
/**
 * Render the Model Create Page
 *
 * @param Request $request
 * @param Response $response
 */
```

should be 

```
/**
 * Render the Schema Create Page
 *
 * @param Request $request
 * @param Response $response
 */
```

All of the javadocs in this file have similar problems

**Comment by cjzamora** [comment]
Done.

Commit: https://github.com/CradlePHP/cradle-system/commit/d01cfe4f6401ea35f1b0c88facca311ea40ce64b
