### ISSUE TITLE
System: Schema Export not allowing redirect_uri

### ISSUE THREAD

**Issue by cblanquera** [CradlePHP/Cradle#166]
https://github.com/CradlePHP/cradle-system/blob/master/src/Schema/controller.php#L604

shows
```
$redirect = '/admin/system/schema/search';
```

then in https://github.com/CradlePHP/cradle-system/blob/master/src/Schema/controller.php#L615
```
return $this->package('global')->redirect($redirect);
```

I was expecting at least the following to be implemented.
```
//this is for flexibility
if ($request->hasStage('redirect_uri')) {
    $redirect = $request->getStage('redirect_uri');
}
```

**Comment by cjzamora** [comment]
Done.

Commit: https://github.com/CradlePHP/cradle-system/commit/d01cfe4f6401ea35f1b0c88facca311ea40ce64b
