### ISSUE TITLE
System: Schema Search Template </table> closing a <div> tag

### ISSUE THREAD

**Issue by cblanquera** [CradlePHP/Cradle#172]
https://github.com/CradlePHP/cradle-system/blob/master/src/Schema/template/search.html#L131

`</table>` should be `</div>`

**Comment by cblanquera** [comment]
same here: https://github.com/CradlePHP/cradle-system/blob/master/src/Schema/template/search.html#L131

**Comment by cjzamora** [comment]
Done.

Commits:

https://github.com/CradlePHP/cradle-system/commit/926613090baec31c32a62516f703619736963551

https://github.com/CradlePHP/cradle-system/commit/91555d4362404925adb9badf623e3d7a916bee79
