### ISSUE TITLE
cradle('global')->queue() doesn't work

### ISSUE THREAD

**Issue by aprilsacil** [CradlePHP/Cradle#180]
cradle('global')->queue() doesn't work. It was declared under cradlephp/cradle-queue.

either replace the ReadMe for queue to:
cradle('cradlephp/cradle-queue')->queue()

or replace it to global.

**Comment by cblanquera** [comment]
Addressed in 2.2

**Comment by cblanquera** [comment]
Should use `$this->package('cradlephp/cradle-queue')->queue()`
