### ISSUE TITLE
Prototype: Front End Builder

### ISSUE THREAD

**Issue by cblanquera** [CradlePHP/Cradle#185]
![image](https://user-images.githubusercontent.com/120378/51297905-5e6d1a80-1a5d-11e9-8c8a-21a7405d648f.png)

A theme should provide a _page.html in order to know what to wrap the site templates around.

![image](https://user-images.githubusercontent.com/120378/51297940-7a70bc00-1a5d-11e9-9cfe-835d99cbef30.png)

![image](https://user-images.githubusercontent.com/120378/51297947-7f357000-1a5d-11e9-953f-8959baa0c6a9.png)

![image](https://user-images.githubusercontent.com/120378/51297954-8492ba80-1a5d-11e9-973f-1bb44a41e642.png)
*see: https://querybuilder.js.org/*

![image](https://user-images.githubusercontent.com/120378/51298196-92950b00-1a5e-11e9-9226-cdf432f94cc6.png)

**Comment by secureweb16** [comment]
Please let me know what I have to do at here ?

**Comment by mimontoy1** [comment]
Please share the detailed list/information of implementation steps required for the front end builder

**Comment by cblanquera** [comment]
Again as this issue is labelled `Prototype` the goal is to prototype a solution to address lessening the need to program the front end. I already completed the prototype, but found that it's easier to create the front end in code first.  Second, I've been looking at https://grapesjs.com/demo.html for the last few days and am trying to find a way to integrate this as well.
