### ISSUE TITLE
Creating database in cradle Not working 

### ISSUE THREAD

**Issue by mimontoy1** [CradlePHP/Cradle#187]
have type same name as you mentioned
What is the name of the SQL database to install?(testing_db): testing_db
What is the SQL server address?(127.0.0.1): 127.0.0.1
What is the SQL server user name?(root): root
What is the SQL server password?(enter for none):
but there is an error occured

PHP Fatal error:  Uncaught Cradle\Storm\SqlException: CREATE TABLE `role` (`role_id` int(10) UNSIGNED NOT NULL auto_increment, `role_name` VARCHAR(255) DEFAULT NULL, `role_slug` VARCHAR(255) DEFAULT NULL, `role_locked` INT(1) unsigned DEFAULT '0', `role_permissions` JSON DEFAULT NULL, `role_admin_menu` JSON DEFAULT NULL, `role_active` INT(1) UNSIGNED DEFAULT '1', `role_created` datetime DEFAULT NULL, `role_updated` datetime DEFAULT NULL, PRIMARY KEY (`role_id`), KEY `role_name` (`role_name`),
KEY `role_slug` (`role_slug`),
KEY `role_locked` (`role_locked`),
KEY `role_active` (`role_active`),
KEY `role_created` (`role_created`),
KEY `role_updated` (`role_updated`)); Query: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'JSON DEFAULT NULL, `role_admin_menu` JSON DEFAULT NULL, `role_active` INT(1) UNS' at line 1 in C:\xampp\htdocs\repo\vendor\cradlephp\storm\src\SqlException.php:54

**Comment by Jacobsemon** [comment]
You need to install mysql version 5.7

**Comment by cblanquera** [comment]
Cradle is primarily designed to use MySQL 5.7. Please check https://cradlephp.github.io/docs/installation.html for the proper requirements.
