### ISSUE TITLE
Undefined variable: dot

### ISSUE THREAD

**Issue by jonijimenez** [CradlePHP/Cradle#188]
![screen shot 2019-01-18 at 4 11 12 pm](https://user-images.githubusercontent.com/8522458/51373851-24bf1100-1b3c-11e9-8cf2-99f26aadc16b.png)

**Comment by cblanquera** [comment]
Cannot recreate the issue. This seems to be a problem with custom code written on top of this file.

https://github.com/CradlePHP/Cradle/blob/2.2/bootstrap/helpers.php#L311 - Shows just a line separator and there is no variable called `$dot` as the error describes.
