### ISSUE TITLE
Add ability to groupBy

### ISSUE THREAD

**Issue by jonijimenez** [CradlePHP/Cradle#189]
Add ability to groupBy columns in a database query

**Comment by cblanquera** [comment]
This fundtion already exists. https://github.com/CradlePHP/Storm/blob/master/src/Search.php#L392-L407

You can access the raw search class by:

```
Schema::('profile')
    ->service('sql')
    ->getResource()
    ->search('profile');
```

If you are referring to adding a groupBy in `cradle-system` `MySqlService->search` please confirm.
