### ISSUE TITLE
Admin page assets are not found.

### ISSUE THREAD

**Issue by risenforward** [CradlePHP/Cradle#192]
Admin pages are broken because admin.css and admin.js are missing.
In cradle-admin page, we can see
<link href="/styles/admin.css" rel="stylesheet" type="text/css" />
<script src="/scripts/admin.js" type="text/javascript"></script>

Should we copy admin.css and admin.js from vendor/cradlephp/cradle-admin/src to public folder?

**Comment by cblanquera** [comment]
You can and recommended if you want to customize the look and feel of the admin, but they should be loading dynamically as per https://github.com/CradlePHP/cradle-admin/blob/2.2/src/controller.php#L19-L33
