### ISSUE TITLE
Wrong Update Profile Icon

### ISSUE THREAD

**Issue by risenforward** [CradlePHP/Cradle#197]
![image](https://user-images.githubusercontent.com/37665595/51754468-3be88c00-2071-11e9-9522-dad26c4ed283.png)

Should be using fas fa-edit icon when updating a profile.

**Comment by risenforward** [comment]
Same issue on Updating Role page

![image](https://user-images.githubusercontent.com/37665595/51755582-e19cfa80-2073-11e9-807b-f83500399866.png)

**Comment by cblanquera** [comment]
Fix now merged:
https://github.com/CradlePHP/cradle-system/pull/45
https://github.com/CradlePHP/cradle-role/pull/6
