### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by betamaxtelecom** [CradlePHP/Cradle#216]
Hello i am getings the follow error

PHP Fatal error:  Uncaught Cradle\Storm\SqlException: CREATE TABLE `role` (`role_id` int(10) UNSIGNED NOT NULL auto_increment, `role_name` VARCHAR(255) DEFAULT NULL, `role_slug` VARCHAR(255) DEFAULT NULL, `role_locked` INT(1) unsigned DEFAULT '0', `role_permissions` JSON DEFAULT NULL, `role_admin_menu` JSON DEFAULT NULL, `role_active` INT(1) UNSIGNED DEFAULT '1', `role_created` datetime DEFAULT NULL, `role_updated` datetime DEFAULT NULL, PRIMARY KEY (`role_id`), KEY `role_name` (`role_name`),
KEY `role_slug` (`role_slug`),
KEY `role_locked` (`role_locked`),
KEY `role_active` (`role_active`),
KEY `role_created` (`role_created`),
KEY `role_updated` (`role_updated`)); Query: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'JSON DEFAULT NULL, `role_admin_menu` JSON DEFAULT NULL, `role_active` INT(1) UNS' at line 1 in /var/www/html/sigen/vendor/cradlephp/storm/src/SqlException.php:54
Stack trace:
#0 /var/www/html/sigen/vendor/cradlephp/stor in /var/www/html/sigen/vendor/cradlephp/storm/src/SqlException.php on line 54

Thanks

**Comment by florespedro133** [comment]
Hi @betamaxtelecom, do you need upgrade MariaDB.
Check this post: https://articlebin.michaelmilette.com/how-to-upgrade-mysql-to-mariadb-in-xampp-in-5-minutes-on-windows/
