### ISSUE TITLE
[BUG] Created schema automatically links to profile table

### ISSUE THREAD

**Issue by jonijimenez** [CradlePHP/Cradle#226]
After creating schema, schema creates a pivot table with profile when there shouldn't be

**To Reproduce**
1. Create a new schema
2. Dont link new schema to profile schema
3. Click Submit
4. Run `bin/cradle install` in terminal

**Actual behavior**
An additional table [new_schema]_profile table is created aside from the new schema

**Expected behavior**
No [new_schema]_profile table is created

**Additional**
Profile and history schema also links to itself generating profile_profile and history_profile respectively

**Comment by cblanquera** [comment]
Noted this will be worked on as soon as we can.

**Comment by cblanquera** [comment]
Thorougly looked through this tried in multiple ways of installing. But I cannot recreate.
