### ISSUE TITLE
On update password field displays md5 value, it should not display, also when password field is empty on update, it should not update the password

### ISSUE THREAD

**Issue by cjestavillo** [CradlePHP/Cradle#23]

**Comment by cjestavillo** [comment]
Password is working as expected.
![image](https://user-images.githubusercontent.com/33796130/38351249-3f2fc82e-38e1-11e8-9897-0d3b271cb605.png)

**Comment by cjestavillo** [comment]
Requested changes in codes had already been implemented.

**Comment by JosephFidelino** [comment]
Tested on Local. Good to close.

![image](https://user-images.githubusercontent.com/26085313/39032065-77fb83aa-449e-11e8-8714-04a92e9ef385.png)
