### ISSUE TITLE
ability to copy field on schema create

### ISSUE THREAD

**Issue by JosephFidelino** [CradlePHP/Cradle#31]

**Comment by cjestavillo** [comment]
- [ ] Upon creating new field, field row must have a copy icon.
- [ ] Cursor must be pointer when hovering/clicking the copy icon.
- [ ] Copy field should be able to copy the update field value.

**Comment by cjestavillo** [comment]
Fixes had already been applied.
Reference commit: https://github.com/CradlePHP/cradle-system/pull/18/commits/1b486489b74d76a8de24465af37b388ae3083b31

**Comment by JosephFidelino** [comment]
Tested on Local. Good to close.

![screen shot 2018-04-18 at 6 33 15 pm](https://user-images.githubusercontent.com/26085313/38927044-17f50728-4337-11e8-9cda-eb5bc520c449.png)
![screen shot 2018-04-18 at 6 33 22 pm](https://user-images.githubusercontent.com/26085313/38927046-18286834-4337-11e8-8e24-498f7776f191.png)
