### ISSUE TITLE
code editor field implementation on schema field type

### ISSUE THREAD

**Issue by JosephFidelino** [CradlePHP/Cradle#32]

**Comment by cjestavillo** [comment]
Code field had been added in field type.
(upon creating/updating a field)
![image](https://user-images.githubusercontent.com/33796130/38364135-f3d56464-3909-11e8-80f9-bfee6069c153.png)
(upon creating/updating in the form)
![image](https://user-images.githubusercontent.com/33796130/38364115-dff9e082-3909-11e8-8f9e-11fb8c400b97.png)

**Comment by JosephFidelino** [comment]
Tested on Local. Good to close.

![screen shot 2018-04-18 at 6 30 38 pm](https://user-images.githubusercontent.com/26085313/38926923-cf6f378a-4336-11e8-97db-69ba0056c92d.png)
![screen shot 2018-04-18 at 6 31 20 pm](https://user-images.githubusercontent.com/26085313/38926924-cffd57fe-4336-11e8-8065-157e025c3072.png)
