### ISSUE TITLE
Restricted Pages

### ISSUE THREAD

**Issue by JosephFidelino** [CradlePHP/Cradle#37]
- [x] Add a `Permission` function in the Menu Build. Only users that have permission on the page (set in the menu builder) are allowed to access it.
- [x] Retain all menus in the menu bar
- [x] If the user opt to browse the restricted page, system should show a notification that the user is not allowed / don't have the permission to access the page.

**Comment by jayn0rm** [comment]
This request is already working. Tagging as `dev complete` status and moving the card to complete.
