### ISSUE TITLE
Empty Field Update

### ISSUE THREAD

**Issue by JosephFidelino** [CradlePHP/Cradle#38]
System should update the optional fields even if the value is empty. Expected result upon submission is that optional field should be empty.

**Comment by cjestavillo** [comment]
This is now working as expected.
Reference commit: https://github.com/CradlePHP/cradle-system/pull/11/commits/14afc7f69f227ba70d853f5b237531274ca30779

**Comment by cjestavillo** [comment]
Requires investigation in STORM module part.

**Comment by cblanquera** [comment]
@cjestavillo can I get a confirmation this is now working?

**Comment by jayn0rm** [comment]
@cblanquera This isn't working yet. I confirmed by creating a new cradle on my local.

**Comment by jayn0rm** [comment]
Tried debugging into the following files but no avail on why empty/null values aren't being accepted during update:

### cradle-system
- events.php
- controller.php
- Formatter.php

### storm
- Model.php
