### ISSUE TITLE
Warning message shows upon creating/updating a module.

### ISSUE THREAD

**Issue by JosephFidelino** [CradlePHP/Cradle#43]
Upon creating/updating a field (with valid option validation) in a module, a warning message shows,
https://files.slack.com/files-pri/T9T1WFFK9-FA4QXBX3Q/screen_shot_2018-04-10_at_10.47.25_am.png

**Comment by cjestavillo** [comment]
To prevent this warning message from appearing, option box will be automatically included once Valid Option had been chosen.
![image](https://user-images.githubusercontent.com/33796130/38616399-8895b3ea-3dc6-11e8-9c7c-2a4f39303eed.png)
Reference commit: https://github.com/CradlePHP/cradle-system/pull/12/commits/07ca4f6860d3a67839d7c1a248c24ba0fbf906b3

**Comment by cjestavillo** [comment]
Referrence commit: https://github.com/CradlePHP/cradle-system/pull/13/commits/dfa9c86c073b4ed86379250c64dca82b36361ed1

**Comment by JosephFidelino** [comment]
Tested on Local. Good to close.

![screen shot 2018-04-18 at 6 23 04 pm](https://user-images.githubusercontent.com/26085313/38926706-366c4d66-4336-11e8-9648-4fa49ce4a1ea.png)
![screen shot 2018-04-18 at 6 23 09 pm](https://user-images.githubusercontent.com/26085313/38926707-36b13eda-4336-11e8-84f8-d9626018fce4.png)
![screen shot 2018-04-18 at 6 23 13 pm](https://user-images.githubusercontent.com/26085313/38926708-36fca532-4336-11e8-889a-5be9e55c7088.png)
