### ISSUE TITLE
Admin Landing Page

### ISSUE THREAD

**Issue by JosephFidelino** [CradlePHP/Cradle#48]
Create a page that is accessible for all.

**Comment by aprilsacil** [comment]
https://github.com/CradlePHP/Cradle/pull/47/commits/03dd49a61723a5d7b56e35345e73b947bd10aa44

**Comment by JosephFidelino** [comment]
Tested on Local. Good to close.

![screen shot 2018-04-18 at 3 00 16 pm](https://user-images.githubusercontent.com/26085313/38916267-448a0b4e-4319-11e8-9445-4948a5b6219f.png)
