### ISSUE TITLE
System Menu Item

### ISSUE THREAD

**Issue by JosephFidelino** [CradlePHP/Cradle#52]
Hide the System Menu Item if the auth_id is not equal to 1

**Comment by cjzamora** [comment]
For Reference: https://github.com/CradlePHP/Cradle/releases/tag/2.0.10

**Comment by cjzamora** [comment]
Instead of hiding the menu if auth_id is 1. I just make the case if the auth_type is equal to `admin`.

**Comment by cblanquera** [comment]
Verified
