### ISSUE TITLE
Fix History Package

### ISSUE THREAD

**Issue by JosephFidelino** [CradlePHP/Cradle#55]
Simplify and Fix history package. Fix directory creation. Fix history detail page
Unable to load the history data

**Comment by cjzamora** [comment]
For Reference: https://github.com/CradlePHP/cradle-history/releases/tag/0.0.11

**Comment by JosephFidelino** [comment]
Tested on Local. Good to close.

![image](https://user-images.githubusercontent.com/26085313/39032541-94441624-44a0-11e8-82aa-eea691f8a188.png)
