### ISSUE TITLE
Fix Role Package

### ISSUE THREAD

**Issue by JosephFidelino** [CradlePHP/Cradle#57]
Fix Role create unable to add role permissions

**Comment by cjzamora** [comment]
For Reference: https://github.com/CradlePHP/cradle-role/commit/b9b9532631635026be017fb5fee3b056308aed02

I was able to fix the problem of add permissions because of handlebars typo problem.

**Comment by JosephFidelino** [comment]
Tested on Local. I was able to create a role and add permission.

![screen shot 2018-04-18 at 2 55 09 pm](https://user-images.githubusercontent.com/26085313/38916101-ac39802c-4318-11e8-86a9-3aaa2aee4b89.png)
![screen shot 2018-04-18 at 2 55 11 pm](https://user-images.githubusercontent.com/26085313/38916102-ac795db4-4318-11e8-8c61-5a242e235d9a.png)
