### ISSUE TITLE
File Link Issue

### ISSUE THREAD

**Issue by JosephFidelino** [CradlePHP/Cradle#61]
The page shows 404 page error when clicking the file name.

**Comment by cjzamora** [comment]
For Reference: https://github.com/CradlePHP/Cradle/commit/16e00ec6add372aba4282401c2fa5dbb3fe13d7e

I added a link to handle the file preview / file download.

**Comment by JosephFidelino** [comment]
Tested on Local. Good to close.

![screen shot 2018-04-18 at 2 51 24 pm](https://user-images.githubusercontent.com/26085313/38915922-13156f3c-4318-11e8-9627-709bfb7cc4f1.png)
![screen shot 2018-04-18 at 2 51 28 pm](https://user-images.githubusercontent.com/26085313/38915923-135ef878-4318-11e8-8124-b16452f30b9a.png)
