### ISSUE TITLE
Export not working after searching

### ISSUE THREAD

**Issue by JosephFidelino** [CradlePHP/Cradle#62]
User tried to export the results of the searched term. However upon exporting, the exported file does not retrieved any data.

**Comment by cjestavillo** [comment]
Issue had been fixed.
**Searching in UI:**
![image](https://user-images.githubusercontent.com/33796130/38796106-f27ae2b6-418c-11e8-838d-6af4805df88b.png)
**Exported file**
![image](https://user-images.githubusercontent.com/33796130/38796148-1cb65092-418d-11e8-879a-ce4ae265a2d1.png)

Reference commit: https://github.com/CradlePHP/cradle-system/pull/14/commits/3bba9ddfda3214b97b8264138e31eb9c319ac9c2

**Comment by cjestavillo** [comment]
Edit some export codes...
Reference commit: https://github.com/cjestavillo/cradle-system/commit/508434b15c8e20450702975fddc62c4a620fa7ae

**Comment by cjestavillo** [comment]
Edit export code...
Reference commit: https://github.com/CradlePHP/cradle-system/pull/15/commits/d7f04578d0b81ec7b4f217bcd1ad326dca7a7648

**Comment by JosephFidelino** [comment]
Tested on Local. Good to close. I used `Authentication` table.

![screen shot 2018-04-18 at 12 55 09 pm](https://user-images.githubusercontent.com/26085313/38912452-f200c766-4307-11e8-83bf-eccbec581c5a.png)
![screen shot 2018-04-18 at 12 55 12 pm](https://user-images.githubusercontent.com/26085313/38912453-f2530396-4307-11e8-88b2-f3e89c69b0f1.png)
