### ISSUE TITLE
Active/Inactive Filter not working properly in Search

### ISSUE THREAD

**Issue by JosephFidelino** [CradlePHP/Cradle#64]
When user searched an active data, inactive data which matches with the search term also shows, and vice-versa.

**Comment by cjestavillo** [comment]
Fixes had already been applied.
_(Before searching an inactive data)_
![image](https://user-images.githubusercontent.com/33796130/38807032-c6cf4c80-41ad-11e8-9d01-a123b8d43b6a.png)
_(After searching an inactive data)_
![image](https://user-images.githubusercontent.com/33796130/38807085-f50effdc-41ad-11e8-86b4-a863f950f7c0.png)

Reference commit: https://github.com/CradlePHP/cradle-system/pull/15/commits/1e36bb0d1a5b10b830caa43581d2238785a9305d

**Comment by JosephFidelino** [comment]
Tested on Local. Good to close. I used `Authentication` table

![screen shot 2018-04-18 at 12 51 42 pm](https://user-images.githubusercontent.com/26085313/38912390-8fb71f7e-4307-11e8-823d-47cc01317030.png)
![screen shot 2018-04-18 at 12 51 56 pm](https://user-images.githubusercontent.com/26085313/38912391-90065ab2-4307-11e8-85da-d89b3e67d669.png)
