### ISSUE TITLE
Change Password Redirect

### ISSUE THREAD

**Issue by JosephFidelino** [CradlePHP/Cradle#68]
Upon submit, system redirects to blank page.

![screen shot 2018-04-18 at 2 57 49 pm](https://user-images.githubusercontent.com/26085313/38916193-0603a6c8-4319-11e8-82a5-f9e0ea032cb4.png)

**Comment by cjzamora** [comment]
This is fixed: https://github.com/CradlePHP/Cradle/commit/a53a2b8f820ea7795bd1a500c0e627495d776259

**Comment by JosephFidelino** [comment]
Tested on Local. Good to close.

![screen shot 2018-04-18 at 6 47 17 pm](https://user-images.githubusercontent.com/26085313/38927635-fe6dca86-4338-11e8-8361-15190a679b3a.png)
![screen shot 2018-04-18 at 6 47 22 pm](https://user-images.githubusercontent.com/26085313/38927636-feb61e1c-4338-11e8-9c78-ff3b37a85d71.png)
