### ISSUE TITLE
Copy Field - Issue

### ISSUE THREAD

**Issue by JosephFidelino** [CradlePHP/Cradle#71]
Issue encounter
- [x] Upon changing the field name and then opt to copy the updated field, system copy the old field name.
- [x] Upon submitting the copied field, action buttons on the new field are not same with the previous field/s

![screen shot 2018-04-18 at 9 27 51 pm](https://user-images.githubusercontent.com/26085313/38934971-b93628fc-434f-11e8-92c9-ffe38a738b14.png)
![screen shot 2018-04-18 at 9 27 55 pm](https://user-images.githubusercontent.com/26085313/38934972-b96d410c-434f-11e8-9b08-f0403d6f23b8.png)
![screen shot 2018-04-18 at 9 27 43 pm](https://user-images.githubusercontent.com/26085313/38934973-b9a152b2-434f-11e8-8956-503221bb6e0c.png)
![screen shot 2018-04-18 at 9 27 47 pm](https://user-images.githubusercontent.com/26085313/38934974-b9d33d86-434f-11e8-86c8-c201dbcf1915.png)
![screen shot 2018-04-18 at 9 28 01 pm](https://user-images.githubusercontent.com/26085313/38934975-ba05dd9a-434f-11e8-8f85-e982a3fb01fe.png)

**Comment by cjestavillo** [comment]
This ticket had already been solved..
Reference ticket: https://github.com/CradlePHP/Cradle/issues/31

**Comment by JosephFidelino** [comment]
Spacing of action buttons are inconsistent.

![image](https://user-images.githubusercontent.com/26085313/38996803-8cf94e84-441e-11e8-9abf-837f75a49080.png)

**Comment by cjestavillo** [comment]
Action buttons spacing had been fixed.
![image](https://user-images.githubusercontent.com/33796130/39052155-a050a422-44dd-11e8-8581-4499255088d4.png)

**Comment by cblanquera** [comment]
all is verified.
