### ISSUE TITLE
Package Page - Details

### ISSUE THREAD

**Issue by JosephFidelino** [CradlePHP/Cradle#72]
Add/rename the following columns:
- [x] Package Version (Composer Lock)
- [x] Installer Version (Vendor)

One of the column is already existing, just rename the column name.

**Comment by cjestavillo** [comment]
Reference issue: Ticket #https://github.com/CradlePHP/Cradle/issues/53

**Comment by cjzamora** [comment]
For Reference: https://github.com/CradlePHP/cradle-install/commit/57ac3513a9c163853e82b4209083fa25882014c8

Please also close the duplicate ticket once done with testing.

**Comment by JosephFidelino** [comment]
Tested on Local. Good to close.

![screen shot 2018-04-19 at 10 06 33 pm](https://user-images.githubusercontent.com/26085313/38996534-fd69a0ca-441d-11e8-8306-4fb070276ec2.png)
