### ISSUE TITLE
Dashboard - Enhancement

### ISSUE THREAD

**Issue by JosephFidelino** [CradlePHP/Cradle#73]
Use the design found in Front End page.

![screen shot 2018-04-18 at 9 40 04 pm](https://user-images.githubusercontent.com/26085313/38935546-2e3cdbe0-4351-11e8-9607-396755a1488c.png)
![screen shot 2018-04-18 at 9 40 31 pm](https://user-images.githubusercontent.com/26085313/38935548-2e755858-4351-11e8-8a22-d882f4fb6396.png)

**Comment by cjzamora** [comment]
For Reference: https://github.com/CradlePHP/Cradle/commit/0dc4d0f1b87bdafff566bc548a3e4bd2e2c69ffd

**Comment by cblanquera** [comment]
Verified.
