### ISSUE TITLE
General Settings - Theme and Menu Configuration

### ISSUE THREAD

**Issue by JosephFidelino** [CradlePHP/Cradle#75]
Add a feature in the General Settings where use can choose theme color and position of menus.

**Comment by cjzamora** [comment]
This is done. Reference: https://github.com/CradlePHP/Cradle/commit/6c2c2841b8ccbeb99d058345b944c47df7b2e6d3

**Comment by cblanquera** [comment]
missing config in template/config in systems package.

**Comment by cjzamora** [comment]
Added the theme to `template/config/settings.php`.

Reference: https://github.com/CradlePHP/cradle-developer/commit/be125429d7ba584a66686c4646b7dacec9f70c9a

**Comment by cblanquera** [comment]
Verified
