### ISSUE TITLE
Pipeline - Numbers

### ISSUE THREAD

**Issue by JosephFidelino** [CradlePHP/Cradle#76]
- If there’s no TOTAL in the URL Parameter, show the percentage bar
- If there’s TOTAL in the URL Parameter, replace percentage bar to TOTAL PER COLUMN (FLOAT)  Which is only number, float, price field (Applicable)
    - Flag http:// . . . . . &total=table_column&price=table_column,table_column
        - 1 column just show the number
        - 2 columns represents price range / number range
            - e.g. 10 - 100
    - Flage http:// . .. . . &currency=PHP
        - To put currency before total and price
            - e.g. PHP100

**Comment by cjestavillo** [comment]
Feature had already been added.

**Comment by cjestavillo** [comment]
Made some modification in range.. Instead of requiring only one column, it will require two columns, as requested in this ticket.
![screenshot from 2018-04-27 18-52-27](https://user-images.githubusercontent.com/33796130/39359346-429f69e8-4a4c-11e8-8ec1-41501b9d532f.png)

**Comment by aprilsacil** [comment]
https://github.com/CradlePHP/Cradle/commit/a2dd6641a23e4645c342d7fd218e547dd636b30d
https://github.com/CradlePHP/cradle-system/commit/9ed7857b48c7aa982a2d0ae774059ad1b2b9c365
https://github.com/CradlePHP/cradle-pipeline/commit/766e6c79b77d66103688f04b45b5af11a8dad464

**Comment by JosephFidelino** [comment]
Tested on newly clone project.

![image](https://user-images.githubusercontent.com/26085313/41082982-9992c1e2-6a62-11e8-9a46-aad634da92de.png)

**Comment by JosephFidelino** [comment]
Updates on Checklist
- [x] Total
- [x] Currency
- [ ] Price (Range)

URL: `http://localhost:8000/admin/system/model/customer/pipeline?show=customer_status&order=customer_priority&total=customer_contract&currency=PHP&price=customer_contract,customer_contract`

![image](https://user-images.githubusercontent.com/26085313/41526432-ce2b30bc-7316-11e8-8e63-9dd0ed3c3835.png)

**Comment by aprilsacil** [comment]
@JosephFidelino i used range instead of price.

**Comment by JosephFidelino** [comment]
Tested. Good to close.

URL: `http://localhost:8000/admin/system/model/customer/pipeline?show=customer_status&order=customer_priority&total=customer_contract&currency=PHP&date=customer_updated&range=customer_contract,customer_contract`

![image](https://user-images.githubusercontent.com/26085313/41575635-012da536-73b6-11e8-89d4-9033d1ed7156.png)
