### ISSUE TITLE
Calendar (Label)

### ISSUE THREAD

**Issue by JosephFidelino** [CradlePHP/Cradle#78]
- Currently it using title/name
- Should used suggestion format

**Comment by cjestavillo** [comment]
The event's title is now using the suggestion format:
![screenshot from 2018-04-25 11-42-39](https://user-images.githubusercontent.com/33796130/39225917-c4b47be8-4881-11e8-952a-27417caec3c9.png)
If there's no suggestion format, it will show no title:
![screenshot from 2018-04-25 11-43-21](https://user-images.githubusercontent.com/33796130/39225919-c6de5e52-4881-11e8-8f2b-0fbdd9ab5630.png)

Reference commits: https://github.com/CradlePHP/Cradle/pull/86/commits/f52ed792cfe694e075e789a1654f359df4073822
https://github.com/CradlePHP/cradle-system/pull/22/commits/666463be3ece34b0e0af5b22a6069ec2c8007607

**Comment by cjestavillo** [comment]
Fix had already been made.

**Comment by cblanquera** [comment]
Verified
