### ISSUE TITLE
Pipeline - Date

### ISSUE THREAD

**Issue by JosephFidelino** [CradlePHP/Cradle#79]
- Not created but use updated
- Show relative format (instead of 2 weeks use 2w)
    - Show on the top right part of the box

**Comment by cjestavillo** [comment]
This feature had already been added (kindly refer to the screenshot):
![screenshot from 2018-04-25 10-58-12](https://user-images.githubusercontent.com/33796130/39226003-417faa26-4882-11e8-9d1a-be0da020b19a.png)

Reference commit: https://github.com/CradlePHP/Cradle/pull/86/commits/f52ed792cfe694e075e789a1654f359df4073822

**Comment by cblanquera** [comment]
remove "Updated: April 24" no needed since the relative updated is on the top right.

**Comment by cjestavillo** [comment]
Updated area had already been removed.
![image](https://user-images.githubusercontent.com/33796130/39359068-fe1a93e8-4a4a-11e8-9f08-e24571a27efc.png)

**Comment by JosephFidelino** [comment]
Please verify if release. Thanks @aprilsacil

**Comment by aprilsacil** [comment]
released. reference commit was attached.

**Comment by JosephFidelino** [comment]
@aprilsacil Date Updated is not displaying in the Pipeline

![image](https://user-images.githubusercontent.com/26085313/41090241-60cbb314-6a76-11e8-9857-dc9f18a636cf.png)
![image](https://user-images.githubusercontent.com/26085313/41090289-7b27485e-6a76-11e8-9f7a-a8ba16ee7110.png)

**Comment by aprilsacil** [comment]
you have to specify via a get param date=column_name @JosephFidelino

**Comment by JosephFidelino** [comment]
Hi @aprilsacil . Noted on this. This is working

URL - `http://127.0.0.1:8888/admin/system/model/customer/pipeline?show=customer_status&order=customer_priority&date=customer_updated`

![image](https://user-images.githubusercontent.com/26085313/41092942-a6ae316c-6a7c-11e8-949e-1b9a14148aed.png)
