### ISSUE TITLE
Pipeline Details (If the relation is 1:1)

### ISSUE THREAD

**Issue by JosephFidelino** [CradlePHP/Cradle#80]
- Title
- Profile / User Assign (If any)
- Profile Image / Avatar (If any) - should be clickable - hover (show name)
    - If Image / Avatar not provided, use the Profile (Should be clickable)
- Last Updated

Profile will only be implemented if there's a flag for profile
- Flag http:// . . . . &profile=true

**Comment by cjestavillo** [comment]
This feature had been added:

- When there's 1:1 relation and user's photo is available:
![screenshot from 2018-04-30 18-25-49](https://user-images.githubusercontent.com/33796130/39423328-f5e4efec-4ca3-11e8-9ae8-499c4666ef40.png)
- When there's 1:1 relation and user's photo is not available:
![screenshot from 2018-04-30 18-21-13](https://user-images.githubusercontent.com/33796130/39423215-6a221390-4ca3-11e8-9eef-aef1374f6f0b.png)
- When there's no 1:1 relation
![image](https://user-images.githubusercontent.com/33796130/39423252-88cd3090-4ca3-11e8-983a-0c0005411d81.png)

**Comment by JosephFidelino** [comment]
`&profile=true` is not working

![image](https://user-images.githubusercontent.com/26085313/41525891-10d1cff4-7315-11e8-80d7-853392aaea99.png)

![image](https://user-images.githubusercontent.com/26085313/41525905-1dbcba30-7315-11e8-8c4d-bec86edf46a4.png)

**Comment by aprilsacil** [comment]
as i have discussed to you before i used,
relations=tablename,tablename1
this is to make the card flexible.
rule of thumb here is that the schema should have a stated relationship to the tables being provided and that it should be a 1:1 relationship

**Comment by JosephFidelino** [comment]
Tested. 1 minor request. Put relation on right align

![image](https://user-images.githubusercontent.com/26085313/41576053-d5bcdf00-73b7-11e8-81a3-30ca1fa12251.png)

**Comment by JosephFidelino** [comment]
Tested. Good to close.

![image](https://user-images.githubusercontent.com/26085313/41586006-4165ffae-73de-11e8-8bb5-fc142698c40e.png)

![image](https://user-images.githubusercontent.com/26085313/41586099-752753a6-73de-11e8-94c2-5767d72717cc.png)
