### ISSUE TITLE
Create/Update Field - Enhancement

### ISSUE THREAD

**Issue by JosephFidelino** [CradlePHP/Cradle#81]
- Sorting/Moving of Options Textbox sequences

![screen shot 2018-04-18 at 9 50 33 pm](https://user-images.githubusercontent.com/26085313/38936102-a5ab34fa-4352-11e8-9118-372ac2e541d3.png)

**Comment by cjestavillo** [comment]
This feature had been added. The user can now re-arrange the options using the up and down button.
![image](https://user-images.githubusercontent.com/33796130/39049039-43b00fba-44d2-11e8-8438-34119f4790ce.png)

**Comment by cblanquera** [comment]
Verified, looks good (though not sure in mobile, but we should open another ticket if that's the case)
