### ISSUE TITLE
Multi Field

### ISSUE THREAD

**Issue by JosephFidelino** [CradlePHP/Cradle#84]
- Under JSON Field
    - From which Schema to pull the field
        - Including the validation
        - Default value
- Like a meta field

Example:
- Category Schema Fields
   - ID
   - Category Name
- Currently Creating - Product Schema
   - Multi Field - Category Schema
- Create a Product (upon submit of Product Schema Create)
   - System displays all fields set in the Product Schema
   - Includes all fields set in the Category Schema

**Comment by jayn0rm** [comment]
Question, do we need all the schemas or only those that are user-created?

Example: Do not include the **_Authentication, History, Profile and Role_** schemas.

**Comment by JosephFidelino** [comment]
Tested. Minor issue: Grouped all fields under `Multi Fields`. This is to avoid confusion

![image](https://user-images.githubusercontent.com/26085313/41838348-c5aac944-7892-11e8-924c-8a94013cd881.png)

![image](https://user-images.githubusercontent.com/26085313/41838412-f7458674-7892-11e8-9fa5-220d6fd017bc.png)
