### ISSUE TITLE
Role Package Fixes

### ISSUE THREAD

**Issue by cjzamora** [CradlePHP/Cradle#85]
- [x] Fix Role Permission checking
- [x] UI Fixes

**Comment by cjzamora** [comment]
For Reference: https://github.com/CradlePHP/cradle-role/commit/e24779844784d476748410edafb42a5b4b512875

Unauthorized Errors is caused by the auth_type not being set to `admin` when accessing admin pages.

**Comment by cblanquera** [comment]
all noted thanks.
