### ISSUE TITLE
Search - Reset (All pages)

### ISSUE THREAD

**Issue by JosephFidelino** [CradlePHP/Cradle#87]
- Upon clicking `Reset`, no action made in the page.

![screen shot 2018-04-25 at 12 43 09 pm](https://user-images.githubusercontent.com/26085313/39226662-63af0084-4886-11e8-9504-44220bd66fbd.png)

**Comment by cjestavillo** [comment]
Reset button is now working.

**Comment by JosephFidelino** [comment]
Tested. Good to close.
