### ISSUE TITLE
Copy Role on Auth

### ISSUE THREAD

**Issue by JosephFidelino** [CradlePHP/Cradle#89]
Upon clicking Copy, system redirects to 404 page.

![screen shot 2018-04-25 at 3 36 36 pm](https://user-images.githubusercontent.com/26085313/39232141-e5fe9d66-489e-11e8-839f-72bcf9f2f591.png)

URL - `http://127.0.0.1:8888/admin/system/model/role/create/auth/1?copy=&redirect_uri=%2Fadmin%2Fsystem%2Fmodel%2Fauth%2F1%2Fsearch%2Frole`

**Comment by cjzamora** [comment]
For Reference: https://github.com/CradlePHP/cradle-system/commit/77b2d2ca3b502ec07e72e97d6c80fb72f0105b39

**Comment by cblanquera** [comment]
Clicking copy goes to create auth instead of create role

**Comment by cjzamora** [comment]
For Reference: https://github.com/CradlePHP/cradle-system/commit/c6702750f7a07d0e336ecb64e9a6be9b6db6ec41

https://github.com/CradlePHP/cradle-role/commit/e7e96755a40719c0047a5e269c741a844ad3a84f

**Comment by JosephFidelino** [comment]
Tested. Good to close.

![image](https://user-images.githubusercontent.com/26085313/41083215-2fb18a00-6a63-11e8-85e9-e5a931d81db8.png)
