### ISSUE TITLE
Auth -> Role -> Create Role - Wrong form

### ISSUE THREAD

**Issue by cblanquera** [CradlePHP/Cradle#92]
Clicking Create Role

![image](https://user-images.githubusercontent.com/120378/39416491-f0f8a3b2-4c7f-11e8-90b8-1e63065fed40.png)

Goes to wrong form

![image](https://user-images.githubusercontent.com/120378/39416514-101b972c-4c80-11e8-977c-47fad3889e08.png)

It should look like 

![image](https://user-images.githubusercontent.com/120378/39416529-2c2a9c2e-4c80-11e8-9c17-0a72ad341a57.png)

**Comment by cjzamora** [comment]
For Reference: https://github.com/CradlePHP/cradle-role/commit/e7e96755a40719c0047a5e269c741a844ad3a84f

https://github.com/CradlePHP/cradle-system/commit/c6702750f7a07d0e336ecb64e9a6be9b6db6ec41

**Comment by JosephFidelino** [comment]
Tested. Good to close.

![image](https://user-images.githubusercontent.com/26085313/41083269-58e61b98-6a63-11e8-9b5b-ef2ed8e771f7.png)
![image](https://user-images.githubusercontent.com/26085313/41083290-65322ee6-6a63-11e8-84eb-f387ba7e51b9.png)
