### ISSUE TITLE
Detail Page

### ISSUE THREAD

**Issue by aprilsacil** [CradlePHP/Cradle#95]
a detail page, and link with an icon on the search page
this is to show the page but not give the user access to update anything

note: no design yet.
just copy the update page's design for now.

**Comment by JosephFidelino** [comment]
Tested. Good to close.

![image](https://user-images.githubusercontent.com/26085313/41149683-cc564450-6b3e-11e8-8ee4-db03756ed6bf.png)

![image](https://user-images.githubusercontent.com/26085313/41149693-d42a81a0-6b3e-11e8-9152-467dc4bcd910.png)
